"""add 2fa field

Revision ID: 31999aef81b3
Revises: 506eca5ca91d
Create Date: 2026-05-16 21:16:30.143873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31999aef81b3'
down_revision = '506eca5ca91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_fa_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('two_fa_enabled')

    # ### end Alembic commands ###
